import Head from 'next/head'

import { useState, useEffect } from 'react'
import axios from 'axios'

import RandomUser from '@components/RandomUser'
import Counter from '@components/Counter'

export default function Home() {
  const [randomUserDataJSON, setRandomUserDataJSON] = useState('')
  const [currentPage, setCurrentPage] = useState(0)
  const [userProfiles, setUserProfiles] = useState([])

  const fetchRandomUserData = (pageNumber = 0) => {
    return axios
      .get(`https://randomuser.me/api?page=${pageNumber}`)
      .then(({ data: { results } }) => {
        console.log(results)
        setRandomUserDataJSON(JSON.stringify(results, undefined, 2))
        setUserProfiles([...userProfiles, ...results])
      })
      .catch((err) => console.log(err))
  }

  useEffect(() => {
    fetchRandomUserData()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-full font-bodyFont">
        {/* <RandomUser
          userProfiles={userProfiles}
          fetchRandomUserData={fetchRandomUserData}
          currentPage={currentPage}
          setCurrentPage={setCurrentPage}
          setUserProfiles={setUserProfiles}
        /> */}
        <pre>{randomUserDataJSON}</pre>
        <Counter />
      </main>
    </>
  )
}
