import Head from 'next/head'
import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import axios from 'axios'

import Button from '@components/Button'
import UserCard from '@components/UserCard'
import next from 'next/types'

export default function Home() {
  const [count, setCount] = useState(0)
  const [nextPageNumber, setNextPageNumber] = useState(1)
  const [userInfos, setUserInfos] = useState([])
  const [randomUserDataJSON, setRandomUserDataJSON] = useState('')

  const fetchUserData = async (pageNumber: number = 1) => {
    try {
      const { data } = await axios.get(
        `https://randomuser.me/api?page=${pageNumber}`
      )
      // console.log(data)
      setUserInfos([...userInfos, ...data.results])
    } catch (err) {
      console.log(err)
    }

    // return axios
    //   .get(`https://randomuser.me/api?page=${pageNumber}`)
    //   .then(({ data }) => {
    //     // let userData = JSON.stringify(data, undefined, 2)
    //     // console.log(userData)
    //     // setRandomUserDataJSON(userData || 'No user data')
    //     setUserInfos([...userInfos, ...data.results])
    //   })
    //   .catch((err) => console.log(err))
  }

  useEffect(() => {
    fetchUserData()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="max-w-containerXS w-full">
        {/* <pre>{randomUserDataJSON}</pre> */}
        {userInfos?.map((userInfo: any, index: number) => {
          return (
            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
              key={index}
            >
              <div>
                Name: {userInfo?.name.first} {userInfo?.name.last}
              </div>
              <img
                src={userInfo?.picture.thumbnail}
                alt="User Picture"
                height="100"
                width="100"
              ></img>
            </motion.div>
          )
        })}
        <button
          className="rounded-lg border-2 border-solid border-black p-4"
          onClick={() => {
            setNextPageNumber(nextPageNumber + 1)
            fetchUserData(nextPageNumber)
          }}
        >
          Get More Users
        </button>
        <Button count={count} setCount={setCount} />
      </main>
    </>
  )
}
