// npm imports
import react, { useState, useRef } from 'react'
import { TaskType } from '@utils/types'

// local imports
import AddItem from '@components/AddItem'
import ItemList from '@components/ItemList'

// type imports
import Head from 'next/head'

export default function Home() {
  const [tasks, setTasks] = useState<TaskType[]>([])
  const uid = useRef(0)

  const addTask = (task: TaskType) => {
    console.log('addTasks fired')
    setTasks([...tasks, { uid: uid.current, val: task, completed: false }])
    uid.current++
  }

  const deleteTask = (id: number) => {
    const temp = [...tasks]
    const res = temp.filter((ele) => ele.uid != id)
    setTasks(res)
  }

  const updateTask = (id: number) => {
    const temp = [...tasks]
    const index = temp.findIndex((ele) => ele.uid === id)
    console.log(index)
    temp[index].completed = true
    console.log(temp)
    setTasks(temp)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-bodyFont">
        <AddItem addTask={addTask} />
        <ItemList
          data={tasks}
          updateTask={updateTask}
          deleteTask={deleteTask}
        />
      </main>
    </>
  )
}
