// npm imports
import react, {useState} from 'react';
import {TaskType} from '@utils/types';

// local imports
import AddItem from '@components/AddItem'
import ItemList from '@components/ItemList'

// type imports
import Head from 'next/head'

export default function Home() {
  const [tasks, setTasks] = useState<TaskType[]>([])

  const addTask = (task: TaskType) => {
    setTasks([...tasks, {val: task, completed: false}])
  }

  const deleteTask = () => {
  }

  const updateTask = (taskQuery: string) => {
    console.log(`attempting to change task to completed`)
    const temp = [...tasks]
    console.log(temp)
    const query = temp.find((ele) => ele.val === taskQuery)
    console.log(query)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-bodyFont">
        <AddItem addTask={addTask}/>
        <ItemList data={tasks} updateTask={updateTask}/>
      </main>
    </>
  )
}
