import Head from 'next/head'

// Importing from other files here vvv
import Navbar from '@components/Navbar'
import Counter from '@components/Counter'
import BasicDropdown from '@components/BasicDropdown'
import AdvancedDropdown from '@components/AdvancedDropdown'
import SearchBar from '@components/SearchBar'
import ApiRequest from '@components/ApiRequest'
import Form from '@components/Form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative font-bodyFont">
        <Navbar />
        <Counter />
        <BasicDropdown />
        <AdvancedDropdown />
        <SearchBar />
        <ApiRequest />
        <Form />
      </main>
    </>
  )
}
