import Head from 'next/head'

import Form from '@components/Form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-full items-center justify-center bg-gradient-to-r from-sky-600 to-indigo-600">
        <Form />
      </main>
    </>
  )
}
